services:
  - type: web
    name: mining-erp
    env: python
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://mining-erp.onrender.com"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        sync: false
