# Generated by Django 5.2.15 on 2026-07-05 20:02

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_number', models.CharField(default=operations.models.inquiry_number, editable=False, max_length=32, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('invoice_loaded', 'Invoice Loaded'), ('ordered', 'Purchase Order Created')], default='sent', max_length=24)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=operations.models.purchase_order_number, editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('receipt_uploaded', 'Receipt Uploaded'), ('loaded_for_transport', 'Loaded for Transport')], default='issued', max_length=32)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='operations.purchaseinquiry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='operations.supplier')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=80)),
                ('receipt_date', models.DateField()),
                ('attachment', models.FileField(upload_to='purchase-receipts/')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='operations.purchaseorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_purchase_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(default=operations.models.requisition_number, editable=False, max_length=32, unique=True)),
                ('item_description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('fr', 'French')], default='en', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted by Procurement'), ('inquiries_sent', 'Purchase Inquiries Sent'), ('purchased', 'Purchased'), ('in_transport', 'In Transportation'), ('delivered', 'Delivered')], default='submitted', max_length=24)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseinquiry',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='operations.requisition'),
        ),
        migrations.AddField(
            model_name='purchaseinquiry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_inquiries', to='operations.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('attachment', models.FileField(upload_to='supplier-invoices/')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='operations.purchaseinquiry')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_number', models.CharField(default=operations.models.transport_number, editable=False, max_length=32, unique=True)),
                ('date', models.DateField()),
                ('vehicle', models.CharField(max_length=80)),
                ('driver', models.CharField(max_length=120)),
                ('container_number', models.CharField(blank=True, max_length=80)),
                ('transit_number', models.CharField(blank=True, max_length=80)),
                ('origin', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=160)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('driver_allowance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('road_toll', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('border_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('escort_fees', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('handling_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('loading', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('offloading', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('storage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('demurrage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('miscellaneous', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('length', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('height', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('cbm_quantity', models.PositiveIntegerField(default=1)),
                ('custom_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('import_duty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('excise_duty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('other_government_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transport_records', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_records', to='operations.purchaseorder')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_records', to='operations.requisition')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_records', to='operations.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportGovernmentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_government_charges', to='operations.transportrecord')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('delivery_note', 'Delivery Note'), ('invoice', 'Invoice'), ('waybill', 'Waybill'), ('bill_of_lading', 'Bill of Lading'), ('customs_declaration', 'Customs Declaration'), ('transit_permit', 'Transit Permit'), ('proof_of_delivery', 'Proof of Delivery')], max_length=32)),
                ('file', models.FileField(upload_to='transport-attachments/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_transport_attachments', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.transportrecord')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
    ]
