# Generated by Django 5.2.15 on 2026-07-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_requisition_urgent_requisitionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('requisitions', 'Requisitions'), ('procurement', 'Procurement Dashboard'), ('suppliers', 'Suppliers'), ('purchase_inquiries', 'Purchase Inquiries'), ('supplier_invoices', 'Supplier Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_receipts', 'Purchase Receipts'), ('transport', 'Transport'), ('transport_reports', 'Transport Reports')], max_length=40)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'module'],
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module_access')],
            },
        ),
    ]
