# Generated by Django 5.2.15 on 2026-07-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_usermoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinquiry',
            name='requisition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_inquiries', to='operations.requisitionitem'),
        ),
        migrations.AddField(
            model_name='purchaseinquiry',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
