# Generated by Django 5.2.15 on 2026-07-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_purchaseinquiry_requisition_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='requisition_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='operations.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
