# Generated by Django 5.2.15 on 2026-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_supplierinvoice_requisition_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_name', models.CharField(default='Mining ERP', max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('address', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('mining-green', 'Mining Green'), ('copper', 'Copper'), ('slate', 'Slate')], default='mining-green', max_length=32)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('zh', 'Chinese')], default='en', max_length=8)),
                ('enable_language_switcher', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application setting',
                'verbose_name_plural': 'Application settings',
            },
        ),
    ]
