# Generated by Django 5.2.15 on 2026-07-10 07:00

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_transport_orders(apps, schema_editor):
    TransportRecord = apps.get_model("operations", "TransportRecord")
    TransportCustomerOrder = apps.get_model("operations", "TransportCustomerOrder")
    for record in TransportRecord.objects.exclude(purchase_order_id=None):
        TransportCustomerOrder.objects.get_or_create(
            transport_id=record.pk,
            purchase_order_id=record.purchase_order_id,
            defaults={"customer_name": ""},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_applicationsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportCustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_transport_orders",
                        to="operations.purchaseorder",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to="operations.transportrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(copy_existing_transport_orders, migrations.RunPython.noop),
    ]
