# Generated by Django 5.2.15 on 2026-07-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_transportcustomerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcustomerorder',
            name='cargo_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='cargo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='cbm_quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='handling_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='loading_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='miscellaneous_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='offloading_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='package_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='storage_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='weight_tons',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransportTransitPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_type', models.CharField(choices=[('border', 'Border'), ('road_toll', 'Road Toll'), ('tax_checkpoint', 'Tax Checkpoint'), ('customs', 'Customs'), ('weighbridge', 'Weighbridge'), ('checkpoint', 'Checkpoint'), ('other', 'Other')], default='border', max_length=32)),
                ('place_name', models.CharField(max_length=160)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_points', to='operations.transportrecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
