# Generated by Django 5.2.15 on 2026-07-10 08:35

from django.db import migrations, models


def copy_existing_transit_amounts(apps, schema_editor):
    TransportTransitPoint = apps.get_model("operations", "TransportTransitPoint")
    category_by_point_type = {
        "border": "border_fee",
        "road_toll": "toll",
        "tax_checkpoint": "tax",
        "customs": "duty",
    }
    name_by_point_type = {
        "border": "Border fee",
        "road_toll": "Road toll",
        "tax_checkpoint": "Tax checkpoint fee",
        "customs": "Customs duty",
        "weighbridge": "Weighbridge fee",
        "checkpoint": "Checkpoint fee",
        "other": "Transit fee",
    }
    for point in TransportTransitPoint.objects.all():
        point.amount = (point.charge_amount or 0) + (point.tax_amount or 0)
        point.fee_category = category_by_point_type.get(point.point_type, "fee")
        point.fee_name = name_by_point_type.get(point.point_type, "Transit fee")
        point.save(update_fields=["amount", "fee_category", "fee_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_transportcustomerorder_cargo_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporttransitpoint",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="transporttransitpoint",
            name="fee_category",
            field=models.CharField(
                choices=[
                    ("fee", "Fee"),
                    ("border_fee", "Border Fee"),
                    ("toll", "Toll"),
                    ("tax", "Tax"),
                    ("duty", "Duty"),
                    ("permit", "Permit"),
                    ("other", "Other"),
                ],
                default="fee",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="transporttransitpoint",
            name="fee_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(copy_existing_transit_amounts, migrations.RunPython.noop),
    ]
