# Generated by Django 5.2.15 on 2026-07-10 08:42

import operations.models
from uuid import uuid4
from django.db import migrations, models


def generated_transit_number():
    return f"TRS-{uuid4().hex[:8].upper()}"


def assign_unique_transit_numbers(apps, schema_editor):
    TransportRecord = apps.get_model("operations", "TransportRecord")
    seen = set()
    for record in TransportRecord.objects.order_by("pk"):
        current = (record.transit_number or "").strip()
        if current and current not in seen:
            seen.add(current)
            continue

        candidate = generated_transit_number()
        while (
            candidate in seen
            or TransportRecord.objects.filter(transit_number=candidate)
            .exclude(pk=record.pk)
            .exists()
        ):
            candidate = generated_transit_number()
        record.transit_number = candidate
        record.save(update_fields=["transit_number"])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_transporttransitpoint_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_unique_transit_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transportrecord",
            name="transit_number",
            field=models.CharField(
                default=operations.models.transit_number,
                editable=False,
                max_length=80,
                unique=True,
            ),
        ),
    ]
