# Generated by Django 5.2.15 on 2026-07-10 09:28

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_transportrecord_transit_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcustomerorder',
            name='billable_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='loading_point',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='loading_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='offloading_point',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='offloading_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporttransitpoint',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransportCustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(default=operations.models.transport_invoice_number, editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='operations.transportcustomerorder')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transport_customer_invoices', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='operations.transportrecord')),
            ],
            options={
                'ordering': ['-invoice_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='TransportCustomerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('direct', 'Direct Customer Charge'), ('shared', 'Shared Fleet Charge'), ('transit', 'Transit/Government Fee'), ('adjustment', 'Adjustment')], max_length=24)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.transportcustomerinvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transportcustomerinvoice',
            constraint=models.UniqueConstraint(fields=('transport', 'customer_order'), name='unique_transport_customer_invoice'),
        ),
    ]
