# Generated by Django 5.2.15 on 2026-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_transportcustomerorder_billable_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('print', 'Print')], default='email', max_length=24),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_message',
            field=models.TextField(blank=True),
        ),
    ]
