# Generated by Django 5.2.15 on 2026-07-10 18:48

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_purchaseorder_delivery_method_purchaseorder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('asset_type', models.CharField(choices=[('machine', 'Machine'), ('vehicle', 'Car / Truck'), ('mine_line', 'Mine line'), ('generator', 'Generator'), ('other', 'Other')], default='machine', max_length=32)),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('mine_line_name', models.CharField(blank=True, max_length=160)),
                ('engine_capacity', models.CharField(blank=True, help_text='Engine size/capacity, for example 2.5L or 320HP.', max_length=80)),
                ('expected_consumption_per_hour', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('responsible_person', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('requisitions', 'Requisitions'), ('procurement', 'Procurement Dashboard'), ('suppliers', 'Suppliers'), ('purchase_inquiries', 'Purchase Inquiries'), ('supplier_invoices', 'Supplier Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_receipts', 'Purchase Receipts'), ('transport', 'Transport'), ('transport_reports', 'Transport Reports'), ('fuel', 'Fuel Department')], max_length=40),
        ),
        migrations.CreateModel(
            name='FuelStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(default=operations.models.fuel_batch_number, editable=False, max_length=32, unique=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('kerosene', 'Kerosene'), ('other', 'Other')], default='diesel', max_length=24)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source_truck', models.CharField(blank=True, max_length=120)),
                ('storage_method', models.CharField(choices=[('drums', 'Drums'), ('jerrycans', 'Jerrycans'), ('tank', 'Tank'), ('mixed', 'Mixed storage')], default='drums', max_length=24)),
                ('container_count', models.PositiveIntegerField(blank=True, default=0)),
                ('litres_received', models.DecimalField(decimal_places=3, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fuel_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_number', models.CharField(default=operations.models.fuel_issue_number, editable=False, max_length=32, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('route_or_location', models.CharField(blank=True, max_length=180)),
                ('driver_operator', models.CharField(max_length=160)),
                ('fuel_before_refill', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('fuel_after_refill', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('litres_issued', models.DecimalField(decimal_places=3, max_digits=14)),
                ('operating_hours', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('odometer_or_hour_meter', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_issues', to='operations.fuelasset')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_fuel_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='operations.fuelstockbatch')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
