# Generated by Django 5.2.15 on 2026-07-10 19:40

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_fuelasset_alter_usermoduleaccess_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaEmbassy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('renewal_requirements', models.TextField(blank=True, help_text='Documents and steps usually needed by this embassy for renewal.')),
                ('standard_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('processing_days', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Visa embassies',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('requisitions', 'Requisitions'), ('procurement', 'Procurement Dashboard'), ('suppliers', 'Suppliers'), ('purchase_inquiries', 'Purchase Inquiries'), ('supplier_invoices', 'Supplier Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_receipts', 'Purchase Receipts'), ('transport', 'Transport'), ('transport_reports', 'Transport Reports'), ('fuel', 'Fuel Department'), ('visas', 'Visa Department')], max_length=40),
        ),
        migrations.CreateModel(
            name='Expatriate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=80, unique=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=140)),
                ('department', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('exited', 'Exited')], default='active', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expatriates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpatriateVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_number', models.CharField(default=operations.models.visa_number, editable=False, max_length=32, unique=True)),
                ('visa_type', models.CharField(choices=[('work', 'Work visa'), ('residence', 'Residence permit'), ('business', 'Business visa'), ('visitor', 'Visitor visa'), ('other', 'Other')], default='work', max_length=32)),
                ('visa_reference', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_status', models.CharField(choices=[('not_started', 'Not started'), ('preparing', 'Preparing documents'), ('submitted', 'Submitted to embassy'), ('approved', 'Approved / renewed'), ('rejected', 'Rejected')], default='not_started', max_length=32)),
                ('renewal_requirements', models.TextField(blank=True)),
                ('renewal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_currency', models.CharField(default='USD', max_length=12)),
                ('reminder_owner', models.CharField(blank=True, max_length=140)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visa_records', to=settings.AUTH_USER_MODEL)),
                ('expatriate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to='operations.expatriate')),
                ('embassy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to='operations.visaembassy')),
            ],
            options={
                'ordering': ['expiry_date', 'expatriate__last_name'],
            },
        ),
    ]
