# Generated by Django 5.2.15 on 2026-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_visaembassy_alter_usermoduleaccess_module_expatriate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expatriatevisa',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expatriatevisa',
            name='last_reminder_stage',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='expatriatevisa',
            name='reminder_email',
            field=models.EmailField(blank=True, help_text='Email address that receives renewal reminders. Falls back to the expatriate email if blank.', max_length=254),
        ),
    ]
