# Generated by Django 5.2.15 on 2026-07-11 06:43

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_expatriatevisa_last_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('requisitions', 'Requisitions'), ('procurement', 'Procurement Dashboard'), ('suppliers', 'Suppliers'), ('purchase_inquiries', 'Purchase Inquiries'), ('supplier_invoices', 'Supplier Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_receipts', 'Purchase Receipts'), ('transport', 'Transport'), ('transport_reports', 'Transport Reports'), ('commercial_documents', 'Business Documents'), ('fuel', 'Fuel Department'), ('visas', 'Visa Department')], max_length=40),
        ),
        migrations.CreateModel(
            name='CommercialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(default=operations.models.commercial_document_number, editable=False, max_length=32, unique=True)),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('proforma_invoice', 'Proforma Invoice'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('delivery_note', 'Delivery Note'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payment_voucher', 'Payment Voucher'), ('statement', 'Account Statement'), ('waybill', 'Waybill'), ('contract', 'Contract / Agreement'), ('other', 'Other Document')], default='quotation', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('client_contact', models.CharField(blank=True, max_length=120)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=60)),
                ('business_reference', models.CharField(blank=True, help_text='Manual reference for any other business or external file.', max_length=160)),
                ('document_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='commercial-documents/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='operations.businessclient')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commercial_documents', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='operations.purchaseorder')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='operations.requisition')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='operations.supplier')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='operations.transportrecord')),
                ('transport_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_documents', to='operations.transportcustomerinvoice')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
