# Generated by Django 5.2.15 on 2026-07-11 07:02

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_businessclient_alter_usermoduleaccess_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('requisitions', 'Requisitions'), ('procurement', 'Procurement Dashboard'), ('suppliers', 'Suppliers'), ('purchase_inquiries', 'Purchase Inquiries'), ('supplier_invoices', 'Supplier Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_receipts', 'Purchase Receipts'), ('transport', 'Transport'), ('transport_reports', 'Transport Reports'), ('commercial_documents', 'Business Documents'), ('financial_reports', 'Financial Reports'), ('fuel', 'Fuel Department'), ('visas', 'Visa Department')], max_length=40),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_number', models.CharField(default=operations.models.financial_record_number, editable=False, max_length=32, unique=True)),
                ('record_type', models.CharField(choices=[('cash_in', 'Cash in'), ('cash_out', 'Cash out'), ('loss', 'Loss')], max_length=24)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=220)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='operations.businessclient')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='operations.commercialdocument')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='operations.supplier')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
