# Generated by Django 4.2.8 on 2026-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_usermoduleaccess_module_financialrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requesting_company',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
