# Generated by Django 4.2.8 on 2026-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_requisition_requesting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='uploaded_document',
            field=models.FileField(blank=True, upload_to='requisitions/'),
        ),
    ]
