# Generated by Django 4.2.8 on 2026-07-14 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_requisition_uploaded_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcustomerorder',
            name='destination',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='document_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='other_charge_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportcustomerorder',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transportcustomerinvoiceline',
            name='line_type',
            field=models.CharField(choices=[('direct', 'Direct Customer Charge'), ('shared', 'Additional Customer Charge'), ('transit', 'Transit/Government Fee'), ('adjustment', 'Adjustment')], max_length=24),
        ),
        migrations.CreateModel(
            name='TransportTransitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('fuel', 'Fuel'), ('driver', 'Driver fee'), ('turn_boy', 'Turn boy'), ('escort', 'Escort fees'), ('fleet', 'Fleet / truck operating cost'), ('maintenance', 'Maintenance'), ('border', 'Border fee'), ('tax', 'Tax'), ('government_document', 'Government document'), ('other', 'Other / custom')], default='other', max_length=32)),
                ('custom_name', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_date', models.DateField(default=django.utils.timezone.localdate)),
                ('allocation_method', models.CharField(choices=[('internal_only', 'Internal only'), ('client_specific', 'Client-specific'), ('distance_shared', 'Distance-based shared'), ('manual', 'Manual allocation')], default='internal_only', max_length=32)),
                ('manual_client_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_costs', to='operations.transportcustomerorder')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_costs', to='operations.transportrecord')),
            ],
            options={
                'ordering': ['cost_date', 'id'],
            },
        ),
    ]
