# Generated by Django 4.2.8 on 2026-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_transportcustomerorder_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcustomerorder',
            name='delivery_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='common_route_end_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='final_destination_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='planned_ferry_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='transit_start_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='turn_boy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='turn_boy_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='vehicle_operating_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transporttransitcost',
            name='cost_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporttransitcost',
            name='km_location',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transporttransitcost',
            name='transit_point',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='transporttransitpoint',
            name='km_location',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transporttransitcost',
            name='allocation_method',
            field=models.CharField(choices=[('internal_only', 'Internal only'), ('client_specific', 'Client-specific'), ('distance_shared', 'Distance-based shared'), ('manual', 'Manual allocation')], default='distance_shared', max_length=32),
        ),
    ]
