# Generated by Django 4.2.8 on 2026-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_transportcustomerorder_delivery_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrecord',
            name='overall_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
    ]
