# Generated by Django 4.2.8 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0022_transportrecord_overall_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="suggested_supplier_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="requisition",
            name="suggested_supplier_contact",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
