# Generated by Django 4.2.8 on 2026-08-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0023_requisition_suggested_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="transportcustomerorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_transport_orders",
                to="operations.requisition",
            ),
        ),
    ]
